### ISSUE TITLE
Rework Survey

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#222] opened 2018-09-13 18:29 UTC
- No submit button for survey answers
- Question 4 is a write-in, it needs a paragraph style box to accommodate approx. 4 lines of text, otherwise everything is cut off. Potentially auto-expanding?
- Title of page should read “Help us improve the game!” not "Survey Thanks/Explanation

![screen shot 2018-09-07 at 12 58 25 pm](https://user-images.githubusercontent.com/8040710/45507881-eada9a00-b758-11e8-8ad3-b97370d3d520.png)

**Comment by stacietaylorcima** [comment] 2018-09-19 03:42
@flipsasser After discussing this issue with @sinabahram today, it was decided that this survey needs to be reworked to comply with accessibility requirements. The survey should be in form of a form with radio buttons so that the user knows what options they have chosen/what questions they have answered. We'll need to keep in mind the feedback mentioned in this ticket as well: copy updates, text_field to text_area with 4 rows, submit button that submits the form. 

@flipsasser Is this something you can tackle or would you like me to move forward with it? 

I am going to simply rename this issue so that we still have this conversation and feedback all in one place.

**Comment by sinabahram** [comment] 2018-09-19 03:50
I’m open to this being toggle buttons, radio buttons, a drop down. Anything semantic, but a link that, when clicked, contacts the server with an answer, and does not indicate to the user it is/has been selected, is not correct, unless of course it’s the only question on a page, at which point that could make sense, but that’s not the case here.

 

Anna, please speak up now, but are you OK with this being styled slightly different to make it accessible? Answers to a question cannot just be links.

**Comment by alavatelliMCA** [comment] 2018-09-19 14:14
First, I don't understand how underlining the correct answer is different than a radio button. Is the issue that underline is not strong enough of an indicator? If the selected answer had a full box around it would that fix the problem?

I am not thrilled about radio buttons because they are ugly, and potentially more confusing if we don't redesign the page. I don't like the idea of dropdowns as these add an extra step to selecting an answer–open dropdown then select an answer, as opposed to simply selecting an answer.

In all, I get the sense that I don't understand the problem completely, so would love to know more so that we can choose a good solution.

**Comment by stacietaylorcima** [comment] 2018-09-19 14:44
This is my bad. When I was testing it, I thought all of the options were underlined, not just selected ones.  I just tested on staging from my phone and you’re right, they underline once selected.

**Comment by stacietaylorcima** [comment] 2018-09-19 14:53
This is my bad. That problem only seems to be local for me. When I was testing it locally with Sina yesterday, I saw that all of the options were underlined, not just selected ones.  I just tested on staging from my phone and you’re right, they underline once selected.

Check this screenshot on an incognito window of my local dev environment: it shows all answers underlined. I'll check out why mine is like that but staging isn't this evening. But it sounds like that's not a problem for anyone else! 

![screen shot 2018-09-19 at 7 48 32 am](https://user-images.githubusercontent.com/25017973/45761225-adef2700-bbe0-11e8-8445-aa1d79aae278.png)

**Comment by sinabahram** [comment] 2018-09-19 18:17
Stacie, we should figure out the difference between your dev environment and staging/live going forward.

 

Anna, the underline is not the issue here. the problem is that the underline should be used to only convey links that are clickable per WCAG and just best practices in general. So, if we have three links, they must remain underlined at all times, regardless of their state e.g. you’ve selected “yes” VS ‘No” to a question. It also just breaks convention in a pretty massive way. links should not be the way you answer things on a page. that’s just not what they are for. they are for linking to other pages, so I’m not ok with these answers being links.

 

What are your thoughts for them to be buttons? Then we can use push buttons, and we can make that accessible, and it won’t be radio buttons or checkboxes or dropdowns?

**Comment by stacietaylorcima** [comment] 2018-09-28 01:39
Flip merged these changes with a closing message of "(closes #222)" but I don't think it reads the close message if it has parenthesis around it because I'm noticing another with a similar close message didn't auto-close. Anyway, I'm going to manually close this.

**Closed by stacietaylorcima** 2018-09-28 01:39 UTC
Labels: scavenger_hunt
