### ISSUE TITLE
Users with no orgs need landing page

### ISSUE THREAD

**Issue by sinabahram** [coyote-team/coyote#559] opened 2021-03-04 19:47 UTC
After we deleted a bunch of orgs from staging, users that had no remaining organizations now get a 404 on login, which makes sense, but we need somewhere for those users to land, especially so that they may create an org if desired.

**Comment by flipsasser** [comment] 2021-03-21 22:26
Duplicate of #558

**Closed by flipsasser** 2021-03-21 22:26 UTC
