### ISSUE TITLE
Apply button overlaps table on resources page

### ISSUE THREAD

**Issue by ruthestarr** [coyote-team/coyote#570] opened 2021-03-23 01:38 UTC
See screenshot 

<img width="1161" alt="screenshot of resources page showing the apply button overlapping the assignment heading in the table of resources" src="https://user-images.githubusercontent.com/53842927/112079521-b11f5100-8b56-11eb-9185-700efc953c49.png">

**Comment by flipsasser** [comment] 2021-03-25 23:47
Oops, that's a regression - this is fixed now!

**Comment by flipsasser** [comment] 2021-04-08 22:51
This was fixed but not closed because whoops

**Closed by flipsasser** 2021-04-08 22:51 UTC
Labels: bug
