### ISSUE TITLE
When batch creating, some resources fail

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#494] opened 2020-06-17 11:14 UTC
When batch creating resources, I end up with:

```
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35216: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/08/06/2010-31-106%20lo%20res.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35217: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/04/Image3LesModes1901small.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35218: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/04/Image4Detail1953-143-18small.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35219: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/04/Image5Detail1987-43-2small.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35220: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/08/28/1902-1-284B%20BT%20front.JPG => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35221: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/08/28/1902-1-284B%20AT.JPG => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35222: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/16/VavassoreEsempario.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35223: http://chsdmdev.wpengine.com/wp-content/uploads/2013/09/IMG_0355_2.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35224: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/25/15562_4af4228924f4215a_z.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35225: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/25/46809931.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35226: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/24/Frederic%20Church%20Mount%20Katahdin%20from%20Lake%20Katahdin%20Maine.JPG => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35227: http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/1.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35228: http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/2.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35229: http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/3.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35230: http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/4.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35231: http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/5.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35232: http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/6.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35233: http://25.media.tumblr.com/tumblr_m7nsnwgaWg1ryv0vso2_500.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] New resource 35234: https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/11/06/clockwork%20butterfly.jpg => ""
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/04/Image2_1987-43-2small.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/11/Girard_Names.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/11/Girard_sky%20dig%20typeface.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/11/2004-13-1_poster.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/11/Oldham%20and%20Coffee%20book.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/13/Sarton%20suite%20in%20Ghent%201911.JPG"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "https://d1eujzb03uflva.cloudfront.net/object-of-the-day/2013/09/13/Sarton%20Writing%20Cabinet%20interior%20%201996-9-1.JPG"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "http://chsdmdev.wpengine.com/wp-content/uploads/2014/01/Amy_And_Sarah.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/Hewitt_Grandparents.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/CU_foundation_building1.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/Abraham.jpg"
[17-Jun-2020 11:07:51 UTC] [Coyote] No resource could be created for "http://chsdmdev.wpengine.com/wp-content/uploads/2013/11/Amy_And_Sarah.jpg"
```

Looking at the request payload, I send an array of `resource` structures, but the returned JSON only contains one resource.

**Comment by flipsasser** [comment] 2020-06-17 20:15
@jkva I'm having trouble reproducing this; can you provide the request payload you're sending?

**Comment by flipsasser** [comment] 2020-06-17 20:28
Nvm I was able to look it up in the logs!

**Comment by flipsasser** [comment] 2020-06-17 23:20
Okay, I'm not really clear on what went wrong - I extracted the JSONAPI renderer and added some regression tests to ensure mixed responses (some successes; some failures) come back cleanly. Can you try again?

One other thing I noticed - are you passing an "Accept: application/json" header on that request? For whatever reason, Rails is claiming it's responding to an HTML request. Which, of course, is irrelevant because it renders JSON no matter what is requested. Just wanted to check.

**Comment by jkva** [comment] 2020-06-18 14:32
So here's a strange thing.

On the first try, I send:

```
(
    [0] => Array
        (
            [name] => https://i.imgur.com/QyYytJ5.png
            [source_uri] => https://i.imgur.com/QyYytJ5.png
            [resource_type] => image
        )

)
```

and I get back HTTP 500 internal server error.

Then I send the same thing _again_:

```
(
    [0] => Array
        (
            [name] => https://i.imgur.com/QyYytJ5.png
            [source_uri] => https://i.imgur.com/QyYytJ5.png
            [resource_type] => image
        )

)
```

and it's 201 created! 

This is consistent behaviour, I've repeated it three times.

**Comment by flipsasser** [comment] 2020-06-18 17:37
From what I found in Sentry, the request body on a number of requests to the upsert endpoint was `********` rather than the above payload. I'm not clear on if something is being mangled by Google's load balancer or the HTTP client, so I'm looking into that now - but my guess is that the payload size is too large for one of them.

In a better world, I would have already wrapped up #489 which would prevent that from returning a 500 and instead return a clear error message as to which parameter that was required was missing (in this case it's the `resources` array). However, that has been delayed due to an ongoing yak shave from #484, which I have upgraded in priority as it's become a linchpin for a bunch of other stuff.

**Comment by jkva** [comment] 2020-06-18 17:42
@flipsasser does that mean that we should cap that batch payload at a certain size for now? I can set it to 30 max, for instance.

**Comment by flipsasser** [comment] 2020-06-18 17:48
@jkva let's try that for now. Unfortunately, googling for `request body "********"` generates very few useful results!

**Comment by flipsasser** [comment] 2020-06-18 17:52
Okay looks like Sentry was scrubbing post data, which made it harder to debug. I'm digging through the Gcloud logs now, and there's a fix to include post data in sentry reports going out now

**Comment by flipsasser** [comment] 2020-06-18 17:59
Alright found the error in the logs. On my end, it looks like the request body has no resources in it for some of the requests:

Request:
```
Started POST "/api/v1/organizations/8/resources/create" for 178.62.213.210 at 2020-06-18 14:19:08 +0000
Processing by Api::ResourcesController#create_many as JSON
Parameters: {"resources"=>[], "organization_id"=>"8", "resource"=>{}}
```

Response:
```json
{
  requestMethod: "POST"
  requestUrl: "https://staging.coyote.pics/api/v1/organizations/8/resources/create"
  requestSize: "505"
  status: 400
  responseSize: "393"
  userAgent: "GuzzleHttp/6.5.1 curl/7.64.0 PHP/7.3.14-1~deb10u1"
  remoteIp: "178.62.213.210"
  serverIp: "216.239.32.21"
  latency: "0.281893264s"
  protocol: "HTTP/1.1"
}
```

**Comment by flipsasser** [comment] 2020-06-18 18:01
Of note, those requests are now coming through with a proper `Accept: application/json` header, so I wonder if the Guzzle client is no longer correctly serializing the data in JSON mode? Hilariously, the `www/form-data` request was well-formed!

**Comment by jkva** [comment] 2020-06-18 18:03
Odd, because that still wouldn't explain why it works the first call and not the second.
Also wouldn't explain why in larger batches, it fails after, say the first 20 of 50.

**Comment by jkva** [comment] 2020-06-18 18:03
I did add the header earlier, so yeah that should be consistently on any API request now.

**Comment by flipsasser** [comment] 2020-06-18 18:07
So there are two issues that I can see. First, per #489, we are not returning useful information for bad requests. Second, we are intermittently receiving bad requests with no clear reason why. I'm going to focus on resolving the bad request error trapping (and the Devise tangent) in order to make sure _any_ API consumer can receive a clear explanation of the problem.

That being said, there could be plenty of actors between your and my endpoints (Guzzle, Google's HTTP layer, Puma, or Rails middleware) emptying out that array on the request. IMO it's worth trying to shrink the payload, since I have little to no control over those pieces, and triple-checking that the payload is going out as intended.

**Comment by flipsasser** [comment] 2020-06-22 22:19
The yak is shaved - you should receive clearly explanations from the API when resource upsert fails (or when any call fails for that matter)

**Comment by flipsasser** [comment] 2020-07-04 16:27
Looks like this hasn't been an issue since we started accepting other resource payload formats. Closing out.

**Closed by flipsasser** 2020-07-04 16:27 UTC
Labels: bug
