### ISSUE TITLE
Data leak issue

### ISSUE THREAD

**Issue by 4-x** [coyote-team/coyote#380] opened 2018-10-05 22:02 UTC
We had two devices in incognito mode, and when one submitted a score then the other navigated to the score submission page, the name entered on the first device was pre-populated in the name input field on the second device.

**Comment by sinabahram** [comment] 2018-10-05 22:28
We need much more info on this, please. can we have exact steps on how to reproduce, please? If it is intermittent or impossible to reproduce, we’re going to need to close this out.

 

also, devices cannot navigate automatically on our site. we have zero JavaScript-based navigation, so it’s very difficult for me to understand how one device automatically navigated to another page without anything being clicked?

**Comment by 4-x** [comment] 2018-10-05 22:46
I should clarify that the devices are not the ones navigating, the users are. And we were only able to reproduce on the same two devices.

The name input field is pre-populated for the user if they have submitted a score before. But when each of these users visited that page on their respective devices, the input field was pre-populated with whatever was last submitted on the other device.

I'm guessing that somehow these two users ended up with the same "current_player_id" in their cookies?

**Comment by sinabahram** [comment] 2018-10-05 23:41
Guessing that’s correct. are you able to reproduce this as of now?

**Comment by stacietaylorcima** [comment] 2018-10-06 04:06
@sinabahram I just completed a game while I was on staging and saw Anna's name. I can get more details, just wanted to get this message out right now.cc @flipsasser

**Comment by alavatelliMCA** [comment] 2018-10-06 04:09
I will note that thus far this issue has only been seen on staging. Though we didn't hit production that hard today because we were more focused on interface so we were primarily using staging.

**Comment by stacietaylorcima** [comment] 2018-10-06 04:10
@sinabahram Ok, cannot reproduce in incognito, but can reproduce in my regular browser. When I begin a game, it says I've completed them all and when I say end game it show me the username: Anna face 1 and the email: a@a.a.

**Comment by flipsasser** [comment] 2018-10-06 05:33
This was happening as a result of staging deploys. Production data would replace staging data, so player IDs would change behind the scenes.

**Closed by flipsasser** 2018-10-06 05:33 UTC
Labels: scavenger_hunt
