### ISSUE TITLE
Multiple unexpected resource groups showing in resource management view

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote#517] opened 2020-09-26 16:26 UTC
When [viewing resource details](https://staging.coyote.pics/organizations/38-job-local-testing-demo-3/resources/248443/edit) a number of resource groups are shown, where only the two existing resource groups for this organization would be expected. 

![screenshot of resource management, showing at least 10 resource groups, some seemingly duplicate](https://user-images.githubusercontent.com/217264/94345346-7b753180-0025-11eb-909e-a565a845686e.png)

**Comment by flipsasser** [comment] 2020-10-19 20:44
Pushed a fix for this a bit back - confirmed it's working correctly

**Comment by sinabahram** [comment] 2020-10-23 21:16
This is not ifxed

**Comment by flipsasser** [comment] 2020-10-24 03:14
Oops, sorry about that. Can you provide an example URL reproducing it?

**Comment by flipsasser** [comment] 2020-10-26 17:27
@sinabahram I can't reproduce this using the example URL Job supplied: https://staging.coyote.pics/organizations/38-job-local-testing-demo-3/resources/248443/edit

Do you have an example where this is happening? What account are you using? I wonder if it's not related to scoping for staff vs. non-staff users

**Comment by ruthestarr** [comment] 2020-10-26 20:49
https://staging.coyote.pics/organizations/40-cooper-hewitt-temporary/resources/256681/edit

<img width="581" alt="Screen Shot 2020-10-26 at 4 47 20 PM" src="https://user-images.githubusercontent.com/53842927/97226934-1e4ad800-17ab-11eb-9afd-720939d0e457.png">

https://staging.coyote.pics/organizations/1-museum-of-contemporary-art-chicago/resources/647/edit

<img width="573" alt="Screen Shot 2020-10-26 at 4 47 51 PM" src="https://user-images.githubusercontent.com/53842927/97226947-24d94f80-17ab-11eb-8ec7-a6ae819ff9a3.png">

**Comment by flipsasser** [comment] 2020-10-26 21:38
That is so weird - here's what it looks like for me:

![image](https://user-images.githubusercontent.com/8594/97231597-ecc91100-1798-11eb-8c71-4eb297c92d70.png)

I'll dig in now and get a fix out ASAP!

**Comment by flipsasser** [comment] 2020-10-26 21:44
Okay, a fix for this is coming down the pike

**Comment by flipsasser** [comment] 2021-03-21 22:11
Shipped forever ago; I forgot to close. Sorry!

**Closed by flipsasser** 2021-03-21 22:11 UTC
Labels: bug
