### ISSUE TITLE
How to deal with images that are removed from website?

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#14] opened 2016-05-19 21:07 UTC
Description Archive with thumbnail so that if image re-uploaded it could be copied over? Potential of re-linking archived descriptions to images...

**Comment by alavatelliMCA** [comment] 2016-06-21 18:46
@sinabahram Would love your thoughts on this question.

**Comment by sinabahram** [comment] 2016-06-21 21:02
I think we need to simply decide who is authoritative with respect to deletion. Obviously the website, I submit, therefore, the question becomes do we wish for a deletion event to occur, an absence to be marked as a deletion (e.g. it was there before but now isn’t), or a field like “deleted: true/false” to be added, etc.

 

Preferences?

**Comment by seeReadCode** [comment] 2016-07-15 17:27
I'm fine either way.  @alavatelliMCA ?

**Comment by alavatelliMCA** [comment] 2016-08-18 15:16
I would like the description to be continue to be stored in coyote and be accessible so that if an image is deleted on the website we haven't lost the writing information, and in theory if the image is reuploaded we can restore the description (even if simply by copy-paste) and not lose that writing work. I think that is the same as what you propose but want to make sure.

That said we now have a central asset repository and deleting images is only on the page level, so this could totally be moot, but a consideration for the public instance since not everyone would play by those rules.

**Comment by seeReadCode** [comment] 2016-08-18 19:26
My impression is that this is a very low priority item so I might punt on this but for the time being here are a couple things would need to be implemented here for the immediate ask:

- [ ] Create "deleted" (maybe we say "archived"?) status for images
- [ ] Expose a "delete" method via API

Then we would eventually want:

- [ ] reasonable workflow for matching descriptions for an archived image to a new image
- [ ] Don't attempt to display the actual image if it has been deleted

**Comment by seeReadCode** [comment] 2017-03-15 22:37
also dupe of #74

**Closed by seeReadCode** 2017-03-15 22:37 UTC
